- name: install ozone
  hosts: all
  become: true

  tasks:

  - name: Ensure linux group "hadoop" exists
    group:
      name: hadoop
      state: present
  - name: Add the user 'ozone' with a primary group of 'hadoop'
    user:
      name: ozone
      state: present
      group: hadoop
      


  - name: create install folder
    file:
      path: /hadoop/app/ozone
      state: directory
      group: hadoop
      mode: '0775'
  - name: create data folder for ozone
    file:
      path: /hadoop/ozone/data
      state: directory
      group: hadoop
      mode: '0775'
  - name: create install folder
    file:
      path: /hadoop/app/ozone/data
      state: directory
      group: hadoop
      mode: '0775'
#  - name: Download ozone
#    get_url:
#      url: https://dlcdn.apache.org/ozone/1.3.0/ozone-1.3.0.tar.gz
#      dest: /hadoop/app/ozone/ozone-1.3.0.tar.gz
#      mode: '0775'
#      checksum: "sha512:65143549fa7b81aa0587757e1482e9ac8d76e8af105c990176981c934088d0f8cf1ea3d4be31a21f707b0f0a8df1f60e41d26f0482207edba98a07ef5d105811"

#      validate_certs: no


  - name: Copy ozone tar
    copy:
      src: ../../HDDS-9207-logs.tar.gz
      dest: /hadoop/app/ozone/HDDS-9207-logs.tar.gz
      owner: ozone
      group: hadoop
      mode: '0775'

  - name: Extract Ozone jar
    unarchive:
      src: /hadoop/app/ozone/HDDS-9207-logs.tar.gz
      dest: /hadoop/app/ozone/
      remote_src: yes
      mode: '0775'
      group: hadoop
      extra_opts: [--strip-components=1]

  - name: Set Ozone for everyone in path
    lineinfile:
      path: /etc/profile
      line: 'export PATH=/hadoop/app/ozone/bin:$PATH' 

  - name: Change ozone script to source /etc/profile
    lineinfile:
      path: /hadoop/app/ozone/bin/ozone
      line: 'source /etc/profile'
      insertafter: .*bash\n

  - name: Copy ozone scripts
    copy:
      src: ./ozone/scripts/
      dest: /hadoop/app/ozone/bin/
      owner: ozone
      group: hadoop
      mode: '0754'

- import_playbook: set_linux_config.yml
