- name: install freeipa client + join domain
  hosts: all
  become: true
  vars:
    admin_pwd: setme

- name: Import external variables
    include_vars:
      file: variables.yml

  tasks:
  - name: check if we need to run it
    stat:
      path: /etc/krb5.conf
    register: krb5file
  - name: Install freeipa client
    yum:
      name: freeipa-client
      state: present
    when: not krb5file.stat.exists  
  - name: Freeipa joind domain
    shell: ipa-client-install --unattended --no-ntp --mkhomedir -p admin@{{ hostname_suffix_upper }} -w {{ admin_pwd }} --domain={{ hostname_suffix }} --server={{ freeipa_hostname }} --realm={{ hostname_suffix_upper }}
    when: not krb5file.stat.exists
  - name: CHange ticket cache config to file instead of keyring
    shell: sed -i 's/KEYRING:persistent:/\/tmp\/krb5cc_/g' /etc/krb5.conf
    when: not krb5file.stat.exists

