
- import_playbook: deploy_ozone.yml
- import_playbook: ozone_update_config.yml
- import_playbook: ozone_init_start_scm.yml
- import_playbook: ozone_init_start_om.yml
- import_playbook: ozone_start_datanode.yml
- import_playbook: ozone_start_s3g.yml
- import_playbook: ozone_start_recon.yml
